name: Deployment Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: "@mindfiredigital/monodog Build, Lint, and Test"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: "Install dependencies"
        run: pnpm install --ignore-scripts

      - name: "Create build"
        run: pnpm run build

      - name: "Lint code"
        run: pnpm run lint

      - name: "Run tests"
        run: pnpm test

      # - name: "Restore changes in json"
      #   run: |
      #     git restore package-lock.json

      - name: "Set Git user name and email"
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

  create-github-release:
    name: Create GitHub release document and publish to npm
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # - name: Install dependencies
      #   run: npm ci

      - name: Semantic Release and npm release
        run: |
          cd packages/monoapp
          npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify .npmignore files
        run: |
          echo "Files included in npm package:"
          npm pack --dry-run
